version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/segmentio/ecs-logs
    steps:
      - checkout
      - run:
          name: install deps
          command: sudo apt-get install libsystemd-dev
      - run:
          name: check out dependencies
          command: make vendor
      - run:
          name: test
          command: make test
